### ISSUE TITLE
Should we add a delegated identity API client to go-spiffe/v2?

### ISSUE THREAD

**Issue by zmt** [spiffe/go-spiffe#241]

**Comment by azdagron** [comment]
Thanks for opening this, @zmt.

The intended scope for go-spiffe is for generic SPIFFE-related code only. Since, Delegated Identity API is a SPIRE-ism, it doesn't really belong here.

However, the [spire-api-sdk](https://github.com/spiffe/spire-api-sdk) repository is precisely where we've intended for high-level client code related to SPIRE APIs to land (currently it just has the protos and generated code).
